[package]
name = "filmreel"
version = "0.5.0"
description = "filmReel parser for Rust"
authors = ["Mikhail Katychev <mkatych@gmail.com>"]
edition = "2018"
license = "GPL-3.0"
readme = "README.md"

documentation = "https://docs.rs/crate/filmreel-rust/"
homepage = "https://crates.io/crates/filmreel-rust"
repository = "https://github.com/Bestowinc/darkroom"

[lib]
name = "filmreel"
path = "src/lib.rs"

[dependencies]
colored = "2.0"
glob  = "0.3"
jql = "2.8"
lazy_static = "1.4.0"
paste = "1.0.5"
pest = "2.1"
pest_derive = "2.1"
pretty_assertions = "0.7.1"
regex = "1.4"
serde = { version = "1.0.118", features = ["derive"] }
serde_json = "1.0"

[dev-dependencies]
rstest = "0.6"
paste = "1.0.5"
