[package]
name = "filmreel"
version = "0.2.0"
description = "filmReel parser for Rust"
authors = ["Mikhail Katychev <mkatych@gmail.com>"]
edition = "2018"
license = "GPL-3.0"
readme = "README.md"

documentation = "https://docs.rs/crate/filmreel-rust/"
homepage = "https://crates.io/crates/filmreel-rust"
repository = "https://github.com/Bestowinc/darkroom"

[lib]
name = "filmreel"
path = "src/lib.rs"

[dependencies]
colored = "1.9"
glob  = "0.3"
jql = "2.5"
lazy_static = "1.4.0"
regex = "1.3.3"
serde = { version = "1.0.104", features = ["derive"] }
serde_json = "1.0.44"

[dev-dependencies]
rstest = "0.5"
