binop_separator = "Back"
blank_lines_lower_bound = 0
blank_lines_upper_bound = 2
brace_style = "PreferSameLine"
color = "Auto"
combine_control_expr = true
comment_width = 80
condense_wildcard_suffixes = false
control_brace_style = "AlwaysSameLine"
disable_all_formatting = false
edition = "2018"
emit_mode = "Files"
empty_item_single_line = true
enum_discrim_align_threshold = 15
error_on_line_overflow = false
error_on_unformatted = false
fn_args_layout = "Tall"
fn_single_line = true
force_explicit_abi = true
force_multiline_blocks = false
format_code_in_doc_comments = true
format_macro_bodies = true
format_macro_matchers = true
format_strings = true
hard_tabs = false
hide_parse_errors = false
ignore = []
imports_indent = "Visual"
imports_layout = "Mixed"
indent_style = "Block"
make_backup = false
match_arm_blocks = true
match_block_trailing_comma = true
max_width = 100
merge_derives = true
merge_imports = true
newline_style = "Auto"
normalize_comments = false
remove_nested_parens = true
reorder_impl_items = true
reorder_imports = true
reorder_modules = true
report_fixme = "Never"
report_todo = "Never"
skip_children = false
space_after_colon = true
space_before_colon = false
spaces_around_ranges = false
struct_field_align_threshold = 15
struct_lit_single_line = true
tab_spaces = 4
trailing_comma = "Vertical"
trailing_semicolon = false
type_punctuation_density = "Compressed"
unstable_features = true
use_field_init_shorthand = false
use_small_heuristics = "Default"
use_try_shorthand = true
version = "Two"
where_single_line = true
wrap_comments = true
